name: Go

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     go-version: [ '1.19', '1.20', '1.21.x' ]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install Dependencies
        run: go mod tidy
      - name: Display Go version
        run: go version
